version: "3.7"

services:
  app:
    build:
        args:
         user: devuser
         uid: 1000
        context: ./
        dockerfile: Dockerfile
    image: ifthenuk/laravel10-apache
    container_name: laravel-apps
    ports:
      - "8070:80"
    restart: unless-stopped
    networks:
      - laravel

networks:
    laravel:
        driver: bridge